# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'uchino-it'
copyright = '2022, Takahito Urai'
author = 'Takahito Urai'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Sphinx document translation with sphinx gettext feature uses these settings:
locale_dirs = ['locale/']
gettext_compact = False


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # A4用紙
    'papersize': 'a4paper',

    # ベースは14pt（LaTeX標準の最大値）
    'pointsize': '14pt',

    # 章開始を片面でもOKに
    'extraclassoptions': 'openany',

    # LaTeXプリアンブル
    'preamble': r'''
        % フォントサイズを1.5倍に拡大（14pt × 1.5 = 21pt相当）
        \makeatletter
        \renewcommand{\normalsize}{\fontsize{21pt}{25pt}\selectfont}
        \renewcommand{\small}{\fontsize{18pt}{22pt}\selectfont}
        \renewcommand{\footnotesize}{\fontsize{15pt}{18pt}\selectfont}
        \renewcommand{\large}{\fontsize{25pt}{30pt}\selectfont}
        \renewcommand{\Large}{\fontsize{30pt}{36pt}\selectfont}
        \renewcommand{\LARGE}{\fontsize{36pt}{43pt}\selectfont}
        \renewcommand{\huge}{\fontsize{43pt}{52pt}\selectfont}
        \renewcommand{\Huge}{\fontsize{50pt}{60pt}\selectfont}
        \makeatother
        \normalsize

        % 行間1.8倍
        \usepackage{setspace}
        \setstretch{1.8}

        % 余白設定（geometryは既に読み込まれているので\geometryで設定変更）
        \geometry{top=25mm, bottom=25mm, left=20mm, right=20mm}

        % 段落間スペース
        \setlength{\parskip}{1.5em}

        % 見出しを大きく（titlesecは既に読み込まれている）
        \titleformat{\chapter}{\Huge\bfseries}{\thechapter}{1em}{}
        \titleformat{\section}{\LARGE\bfseries}{\thesection}{1em}{}
        \titleformat{\subsection}{\Large\bfseries}{\thesubsection}{1em}{}

        % シンプルなヘッダー・フッター（fancyhdrは既に読み込まれている）
        \pagestyle{fancy}
        \fancyhf{}
        \fancyfoot[C]{\Large\thepage}
        \renewcommand{\headrulewidth}{0pt}

        % 画像の最大高さを制限（縦長画像がページに収まるように）
        \makeatletter
        \setlength{\spx@image@maxheight}{0.7\textheight}
        \makeatother
    ''',
}
